version: '3.8'

services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html/src
      - ./src/index.html:/usr/share/nginx/html/index.html
    # Uncomment if your app needs network access to a target
    # network_mode: host
